name: kointos
description: A crypto portfolio and social trading platform.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core utilities
  http: ^1.2.1
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  path: ^1.9.0
  uuid: ^4.4.0
  logger: ^2.4.0
  json_annotation: ^4.9.0
  get_it: ^7.7.0
  
  # UI & Animation
  flutter_animate: ^4.5.0
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  flutter_markdown: ^0.7.3
  markdown: ^7.2.2
  
  # Image & Media
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  
  # Navigation & Utils
  url_launcher: ^6.3.0
  share_plus: ^9.0.0
  
  # AWS Amplify (Compatible version)
  amplify_flutter: ^2.4.0
  amplify_auth_cognito: ^2.4.0
  amplify_api: ^2.4.0
  amplify_storage_s3: ^2.4.0
  
  # State Management & Architecture
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # Networking & API
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  
  # Tutorial & Onboarding
  introduction_screen: ^3.1.12
  tutorial_coach_mark: ^1.2.11
  
  # Chat/AI Features
  flutter_chat_ui: ^1.6.13
  
  # Animations & Effects
  confetti: ^0.7.0
  
  # Charts & Graphs
  fl_chart: ^0.68.0
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - amplify_outputs.json